media:
  input: src/media
  output: media
content:
  - name: news
    label: News
    path: src/pages/news
    type: collection
    view:
      fields: [heroImage, title, pubDate]
    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: pubDate
        label: Publication Date
        type: date
        required: true
        options:
          format: yyyy-MM-dd

      - name: heroImage
        label: Hero Image
        type: image
